# To execute this docker compose yml file use `docker compose -f docker-compose-h2.yml up -d `
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-h2.yml down`
services:
  chaintest:
    image: anshooarora/chaintest:latest
    container_name: chaintest
    environment:
      - "SPRING_PROFILES_ACTIVE=h2"
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./data/db
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
    ports:
      - 80:80