# To execute this docker compose yml file use `docker compose -f docker-compose-Android.yml up -d `
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-Android.yml down`
version: '3'
services:
  appium:
    image: appium/appium
    ports:
      - "4723:4723"
    volumes:
      - ./app:/app
    environment:
      - ANDROID_HOME=/opt/android-sdk-linux
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    command: appium

  android:
    image: budtmo/docker-android-x86-8.1
    depends_on:
      - appium
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5555:5555"
    environment:
      - DEVICE="Samsung Galaxy S6"
      - APPIUM=true
      - APPIUM_HOST=appium
      - APPIUM_PORT=4723
    volumes:
      - ./app:/root/tmp

