name: Selenium Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER

      - name: Check Docker installation
        run: |
          docker --version
          docker info

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Check Docker Compose installation
        run: docker-compose --version

      - name: Pull Docker images
        run: |
          docker pull selenium/hub:latest
          docker pull selenium/node-chrome:latest
          docker pull selenium/node-firefox:latest
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Start Selenium Grid
        run: docker-compose -f .github/workflows/docker-compose.yml up -d

      - name: Wait for Selenium Grid to be ready
        run: |
          max_retries=30
          retry_interval=10
          for i in $(seq 1 $max_retries); do
            if curl -sSL "http://localhost:4444/wd/hub/status" | jq -r '.value.ready' | grep "true" > /dev/null; then
              echo "Selenium Grid is up and ready"
              exit 0
            fi
            echo "Waiting for Selenium Grid to be ready... (Attempt $i/$max_retries)"
            sleep $retry_interval
          done
          echo "Selenium Grid did not become ready in time"
          exit 1

      - name: Run TestNG Suite
        run: mvn clean test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-output/**/*.xml
            test-output/**/*.trx
            test-output/**/*.json

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
         name: Selenium Test Results
         path: test-output/**/*


      - name: Stop Selenium Grid
        if: always()
        run: docker-compose -f .github/workflows/docker-compose.yml down
