name: Selenium Tests
permissions:
  checks: write
  contents: read

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Store docker image cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Set up Selenoid with X11 support
        run: |
          docker pull docker pull selenoid/vnc_chrome:128.0
          docker pull selenoid/video-recorder:latest-release
          curl -s https://aerokube.com/cm/bash | bash
          ./cm selenoid start --vnc

      - name: Start Selenoid UI
        run: |
          ./cm selenoid-ui start

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: restore

      - name: Run tests with maven
        run: mvn test

      - name: Publish TestNG Report
        uses: starburstdata/action-testng-report@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/testng-results.xml"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Selenium Test Results
          path: test-output/**/*

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: save

      - name: Stop Selenoid
        if: always()
        run: |
          ./cm selenoid stop
          ./cm selenoid-ui stop
