name: Selenium Tests

permissions:
  checks: write
  contents: read

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build with Maven
        run: mvn -B clean test

#      - name: Store docker image cache
#        uses: satackey/action-docker-layer-caching@v0.0.11
#        continue-on-error: true


#      # Solution 1: Install X11 utilities
#      - name: Install X11 utilities
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y x11-xserver-utils
#
#      # Solution 2: Set up Xvfb
#      - name: Set up Xvfb
#        run: |
#          sudo apt-get install -y xvfb
#          Xvfb :99 -ac &
#          export DISPLAY=:99
#
#      # Solution 3: Configure tests for headless mode
#      - name: Set Java AWT Headless Property
#        run: echo "JAVA_OPTS=-Djava.awt.headless=true" >> $GITHUB_ENV
#
#      - name: Set up Selenoid with X11 support
#        run: |
#          docker pull selenoid/vnc_chrome:128.0
#          docker pull selenoid/video-recorder:latest-release
#          docker pull selenium/standalone-chrome:latest
#          curl -s https://aerokube.com/cm/bash | bash
#          ./cm selenoid start --vnc
#
#      - name: Start Selenoid UI
#        run: |
#          ./cm selenoid-ui start

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: restore
#      - name: Set up Selenium Grid
#        run: |
#            wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.27.0/selenium-server-4.27.0.jar
#            java -jar selenium-server-4.27.0.jar hub &
#            java -jar selenium-server-4.27.0.jar node --detect-drivers true &

#      - name: Run tests with maven
#        run: mvn test
#        env:
#          JAVA_OPTS: ${{ env.JAVA_OPTS }}

      - name: Publish TestNG Report
        uses: starburstdata/action-testng-report@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/testng-results.xml"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Selenium Test Results
          path: test-output/**/*

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: save

#      - name: Stop Selenoid
#        if: always()
#        run: |
#          ./cm selenoid stop
#          ./cm selenoid-ui stop
